
import { CommunityCards } from "../components/CommunityCards"

export const Community = () => {

    const sendMessage = () => {
        window.open(`https://api.whatsapp.com/send?phone=573217200994&text=Hola, necesito soporte`, '_blank')
    }

    return(
        <div>
        <section className=" h-screen">
           <div className=" absolute top-0 h-full w-full overflow-hidden" >
               <img width='100%' src="./community_image.jpeg" alt=" A girl with Vr glasses  " />
           </div>
           
           <div className="absolute top-0 h-full w-full flex flex-col justify-center">
               <div className="backdrop-blur-sm text-white drop-shadow-[2px_2px_2px_#00e1ff]">
                   <h1 className=" w-full text-center text-9xl  ">
                       COMUNIDAD
                   </h1>

               </div>
           </div>
       </section>
       <section className="flex justify-around px-40">
                <CommunityCards community='gamer' source='./gamer.jpeg' alternative='face and planets generated by IA' title='UNETE A LA COMUNIDAD GAMER' caption='Si eres un apasionado del gaming esta comunidad es perfecta para ti, puedes interactuar con otros jugadores hasta unirte a un equipo competitivo.' />
                <CommunityCards community='de desarrolladores' source='./developer.jpeg' alternative='face and planets generated by IA' title='UNETE A LA COMUNIDAD DE DESARROLLADORES' caption='Nuestra comunidad cuenta con desarrolladores en todas las áreas de programación, desde ciencia de datos hasta desarrollo movil, unete para seguir mejorando juntos.' />
                <CommunityCards community='de deportistas' source='./excercise.jpeg' alternative='face and planets generated by IA' title='UNETE A LA COMUNIDAD DE DEPORTISTAS' caption='Una de las mejores comunidades para hacer deporte, puedes hacer deporte en el metaverso con tus compañeros apoydaos en la realidad virtual y/o mixta, tambien puedes asistir a las quedadas en diferentes ciudades.' />            
            </section>
            <section className="flex justify-around px-40">
                <div className="  my-20 border-[1px] border-slate-500 hover:shadow-2xl hover:shadow-cyan-500 bg-white hover:cursor-pointer" >
                    <figure className="flex" onClick={sendMessage}>
                        <figcaption className="w-[200px] text-center flex flex-col justify-center">
                            <h2 className="pb-10">
                                SOPORTE
                            </h2>
                            <p className="mx-4">
                                Si tienes alguna duda o si requieres soporte puedes comunicarte con nosotros y te ayudaremos encantados.
                            </p>
                        </figcaption>
                        <img width="500px" className="" src="./fixer.jpeg" alt="a photo of the earth" />
                    </figure>
                    
                </div>
            </section>
   </div>
    )
}