
import {useNavigate} from 'react-router-dom'

import { HomeCard } from "../components/HomeCard"

export const Home = () => {

    const navigate = useNavigate()

    return (
        <>
            <section className=" h-screen">
                <div className=" absolute top-0 h-full w-full overflow-hidden" >
                    <img  width='100%' src="./home_image.jpeg" alt=" A girl with Vr glasses  " />
                </div>
                
                <div className="absolute top-0 h-full w-full flex flex-col justify-center">
                    <div className="backdrop-blur-sm text-white drop-shadow-[2px_2px_2px_#00e1ff]">
                        <h1 className=" w-full text-center text-9xl  ">
                            GAMING METAVERSE...
                        </h1>
                        <h2 className=" w-full text-center text-6xl ">
                            ... A UNIQUE EXPERIENCE
                        </h2>
                    </div>
                   
                </div>
            </section>
                
            <section className="flex justify-around px-40">
                <HomeCard source='./11.png' alternative='face and planets generated by IA' title='MARKETPLACE' caption='You can enter to make purchases in our virtual store for both software and hardware, all completely certified and of the best quality.' navigate='marketplace' />
                <HomeCard source='./2.jpg' alternative='face and planets generated by IA' title='ONLINE GAMES' caption='You can try games developed to run in your web browser without having to install external products.' navigate='games' />
                <HomeCard source='./44.png' alternative='face and planets generated by IA' title='GAMING ACADEMY' caption='Watch totally free courses on topics that may be of interest to you.' navigate='learning' />            
            </section>
            <section className="flex justify-around px-40">
                <div className="  my-20 border-[1px] border-slate-500 hover:shadow-2xl hover:shadow-cyan-500 bg-white hover:cursor-pointer" onClick={() => navigate('/community')} >
                    <figure className="flex">
                        <figcaption className="w-[200px] text-center flex flex-col justify-center">
                            <h2 className="pb-10">
                                COMMUNITY
                            </h2>
                            <p className="mx-4">
                                Here you can join one of our communities to meet people with common interests or contact us
                            </p>
                        </figcaption>
                        <img width="500px" className="" src="./3.jpg" alt="a photo of the earth" />
                    </figure>
                    
                </div>
            </section>
        </>
    )
}