
import {useNavigate} from 'react-router-dom'

import { HomeCard } from "../components/HomeCard"

export const Home = () => {

    const navigate = useNavigate()

    return (
        <>
            <section className=" h-screen">
                <div className=" absolute top-0 h-full w-full overflow-hidden" >
                    <img  width='100%' src="./home_image.jpeg" alt=" A girl with Vr glasses  " />
                </div>
                
                <div className="absolute top-0 h-full w-full flex flex-col justify-center">
                    <div className="backdrop-blur-sm text-white drop-shadow-[2px_2px_2px_#00e1ff]">
                        <h1 className=" w-full text-center text-9xl  ">
                            METAVERSO GAMING...
                        </h1>
                        <h2 className=" w-full text-center text-6xl ">
                            ... A UNIQUE EXPERIENCE
                        </h2>
                    </div>
                   
                </div>
            </section>
                
            <section className="flex justify-around px-40">
                <HomeCard source='./11.png' alternative='face and planets generated by IA' title='MARKETPLACE' caption='Puedes ingresar para realizar compras en nuestras tienda virtual tanto de software como de hardware, todo completamente certificado y de la mejor calidad.' navigate='marketplace' />
                <HomeCard source='./2.jpg' alternative='face and planets generated by IA' title='JUEGOS EN LINEA' caption='Puedes probar juegos desarrollados para correr en tu navegador web sin necesidad de instalar productos externos.' navigate='games' />
                <HomeCard source='./44.png' alternative='face and planets generated by IA' title='HERRAMIENTAS DE APRENDIZAJE' caption='Mira cursos totalmente gratuitos de temas que te pueden resultar de interes.' navigate='learning' />            
            </section>
            <section className="flex justify-around px-40">
                <div className="  my-20 border-[1px] border-slate-500 hover:shadow-2xl hover:shadow-cyan-500 bg-white hover:cursor-pointer" onClick={() => navigate('/community')} >
                    <figure className="flex">
                        <figcaption className="w-[200px] text-center flex flex-col justify-center">
                            <h2 className="pb-10">
                                COMUNIDAD
                            </h2>
                            <p className="mx-4">
                                Aqui puedes unirte a una de nuestras comunidades para conocer a personas con intereses comunes o contactarte con nosotros
                            </p>
                        </figcaption>
                        <img width="500px" className="" src="./3.jpg" alt="a photo of the earth" />
                    </figure>
                    
                </div>
            </section>
        </>
    )
}